# 1 - first word priority
# 2 - second word priority
# 3 - consider as one
# 12 - both words important
# 0 - ignore
def main_word():
    dependencies = {
    'root' : 2,
    'dep' : 1,
    'aux' : 0,
    'auxpass' : 0,
    'abbrev' : 0,
    'attr' : 0,
    'cop' : 1,
    'arg' : 12,
    'agent' : 12,
    'comp' : 12,
    'acomp' : 2,
    'ccomp' : 0,
    'xcomp' : 12,
    'obj' : 12,
    'dobj' : 12,
    'iobj' : 0,
    'pobj' : 0,
    'subj' : 12,
    'nsubj' : 12,
    'nsubjpass' : 12,
    'csubj' : 12,
    'csubjpass' : 12,
    'infmod' : 12,
    'cc' : 0,
    'conj' : 0,
    'expl' : 0,
    'mod' : 0,
    'amod' : 2,
    'appos' : 0,
    'advcl' : 12,
    'det' : 0,
    'predet' : 0,
    'preconj' : 0,
    'vmod' : 0,
    'mwe' : 12,
    'mark' : 1,
    'advmod' : 2,
    'neg' : 12,
    'rcmod' : 12,
    'quantmod' : 0,
    'nn' : 0,
    'npadvmod' : 0,
    'tmod' : 0,
    'num' : 0,
    'number' : 0,
    'prep' : 0,
    'poss' : 0,
    'possessive' : 0,
    'prt' : 3,
    'parataxis' : 12,
    'goeswith' : goes with
    'punct' : 0,
    'ref' : 0,
    'sdep' : 1,
    'xsubj' : 1,
    'rel' : 1,
    'purpcl' : 12,
    'measure' : 12
    }
